version: '3.7'

services:
  web-app:
    container_name: web-app
    build:
      context: .
      dockerfile: Dockerfile
      target: web-app
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
  web-app-storybook:
    container_name: web-app-storybook
    build:
      context: .
      dockerfile: Dockerfile
      target: web-app-storybook
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 6006:6006
    environment:
      - CHOKIDAR_USEPOLLING=true