.PHONY: env-unix

unix: env-unix

env-unix:
	@echo "Copying example env file to .env"
	@cp ./.env.example ./.env

windows: env-windows

env-windows:
	@echo "Copying example env file to .env"
	@xcopy .\.env.example .\.env /Y
