export default {
	diplomacyWiki: "https://en.wikipedia.org/wiki/Diplomacy_(game)",
	allanBCalhamerWiki: "https://en.wikipedia.org/wiki/Allan_B._Calhamer",
	riskWiki: "https://en.wikipedia.org/wiki/Risk_(game)",
	diplomacyRules: "https://en.wikibooks.org/wiki/Diplomacy/Rules",
	zeroSumGameWiki: "https://en.wikipedia.org/wiki/Zero-sum_game",
	diplicityGithub: "https://github.com/zond/diplicity",
	godipGithub: "https://en.wikibooks.org/wiki/Diplomacy/Rules",
	hostedDiplicity: "https://diplicity-engine.appspot.com/",
	restWiki: "https://en.wikipedia.org/wiki/Representational_state_transfer",
	jsonWiki: "https://en.wikipedia.org/wiki/JSON",
	androidApp: "https://play.google.com/store/apps/details?id=se.oort.diplicity",
	oldVersions: "https://github.com/zond/android-diplicity/releases",
	webVersion: "https://diplicity.com",
}